---
- name: Generic systemd unit
  ansible.builtin.copy:
    src: tmux@.service
    dest: /etc/systemd/system/tmux@.service
    mode: "0664"
  tags:
    - systemd
    - unit

- name: Systemd service stat
  ansible.builtin.stat:
    path: /etc/systemd/system/tmux@.service
  register: gs
  tags:
    - systemd
    - unit
    - stat

- name: Systemd variables file
  ansible.builtin.template:
    src: tmux.session.j2
    dest: /etc/default/tmux.{{ item.name }}
    mode: "0664"
  loop: "{{ tmux_system_sessions }}"
  tags:
    - systemd
    - variable

- name: Tmux init script
  ansible.builtin.template:
    src: tmux.ini.j2
    dest: "{{ item.ini_file }}"
    mode: "0664"
  loop: "{{ tmux_system_sessions }}"
  tags:
    - systemd
    - init

- name: Systemd service
  ansible.builtin.systemd:
    name: tmux@{{ item.name }}
    enabled: "{{ item.enabled | default(true) }}"
    state: "{{ item.state | default('started') }}"
    daemon_reload: true
  loop: "{{ tmux_system_sessions }}"
  when:
    - gs.stat.exists
  tags:
    - systemd
    - service
